### ISSUE TITLE
Broken documentation link in Readme

### ISSUE THREAD

**Issue by scottpantall** [CommunityToolkit/Datasync#68] opened 2024-08-19 01:24 UTC
## To Reproduce

1. Under "Getting Started" click on `documentation` link in "Please take a look at the tutorials included in our [documentation](https://communitytoolkit.github.io/Datasync)."
2. Get a "404 - There isn't a GitHub Pages site here" page.

## Expected behavior

We get directed to a tutorial

**Comment by adrianhall** [comment] 2024-08-26 20:12
Dupe of #30

**Closed by adrianhall** 2024-08-26 20:12 UTC
Labels: Bug, Documentation
